baremes-ipp-prelevements-sociaux-social-security-contributions.xlsx:
    name: prelevements_sociaux
    ignore_sheets:
        - Sommaire (FR)
        - Outline (EN)
        - Abréviations
        - CNRACL
        - IRCANTEC
        - FILLON
        - CSG-REMPLACEMENT
        - ASSIETTE_PU
        - AUBRYI
        - CITS  # absent du sommaire
baremes-ipp-taxation-capital.xlsx:
    name: taxation_capital
    ignore_sheets:
        - Sommaire (FR)
        - Outline (EN)
baremes-ipp-chomage-unemployment.xlsx:
    name: chomage
    ignore_sheets:
        - Sommaire FR
        - Outline EN
baremes-ipp-retraites-pensions.xlsx:
    name: retraites
    summary_depth: 3
    ignore_sheets:
        - Sommaire (FR)
        - Outline (EN)
        - AOD_RG  # valeurs de type "60 ans 9 mois"
        - AAD_RG  # idem
        - Coeff_mino_arrco  # Valeur en fonction de l'age de départ à la retraite, pas de la date
        - Coeff_mino_agirc  # Valeur en fonction de l'age de départ à la retraite, pas de la date
        - Coeff_temp  # Valeur en fonction de l'age de départ à la retraite, pas de la date
        - LA-FP-S  # valeurs de type "60 ans 9 mois"
        - LA-FP-A  # idem
        - AOD-FP-S  # idem
        - AOD-FP-A  # idem
        - AAD-FP  # valeurs de type "Limite d'âge - 4 trimestres"
        - RAM  # 2 colonnes '1948' qui contiennent des valeurs différentes
baremes-ipp-marche-du-travail-labour-market.xlsx:
    name: marche_travail
    ignore_sheets:
        - Sommaire (FR)
        - Outline (EN)
baremes-ipp-tarification-energie-logement.xlsx:
    name: tarifs_energie
    ignore_sheets:
        - Sommaire (FR)
        - Outline (EN)
baremes-ipp-taxation-indirecte.xlsx:
    name: taxation_indirecte
    ignore_sheets:
        - Sommaire (FR)
        - Outline (EN)
        - TVA par produit # valeurs en fonction du produit, pas de la date
        - Major régionale TICPE gazole  # absent du sommaire
        - Major régionale TICPE super  # absent du sommaire
baremes-ipp-impot-revenu-income-tax.xlsx:
    name: impot_revenu
    ignore_sheets:
        - Sommaire (FR)
        - Outline (EN)
        - Barème IGR  # Une ligne = une tranche, pas une date. TODO: Signaler erreur probable en J5
        - reduc_exceptionnelle  # absent du sommaire
        - abat  # absent du sommaire
    ignore_columns:
        abat: ['I', 'J']  # Empty columns
        charg_deduc: ['O']  # valeur "pas de limite" non parsable
        taxe_prop: ['J']  # valeur est une string (Voir S&EF...)
baremes-ipp-prestations-sociales-social-benefits.xlsx:
    name: prestations_sociales
    summary_depth: 3
    ignore_sheets:
        - Sommaire (FR)
        - Outline (EN)
        - AA_plaf  # Pas de données, "Mêmes plafonds que pour l'APJE"
        - API_FL  # Pas de données après 2007: "Même forfait logement que le RMI"
    ignore_columns:
        PAJE_CM2: ['D']  # Pas de données: "Mêmes conditions..."
        AL_plaf_acc: ['Z']  # Pas de valeurs numériques, mais "Après le 30/09/2014"
        AL_loc2: ['AF']  # Pas de données:  "Même loyers que les plafonds pour la zone 2"
        ASI_cond:
            - B  # "Mêmes paramètres que pour l'ASPA"
            - C  # "Pas d'âge minimum"
